In [18]:
import pandas as pd
from tqdm.notebook import tqdm, trange
from IPython.core.display import display, HTML

In [19]:
df = pd.read_csv('BPI_2012.csv')

In [20]:
df['concept:name S1'] = df['concept:name'].shift(1)
df['concept:name S2'] = df['concept:name'].shift(2)
df['lifecycle:transition S1'] = df['lifecycle:transition'].shift(1)
df['lifecycle:transition S2'] = df['lifecycle:transition'].shift(2)
df['case_id S1'] = df['case_id'].shift(1)
df['case_id S2'] = df['case_id'].shift(2)

df[['concept:name S1','concept:name S2','lifecycle:transition S1', 'lifecycle:transition S2', 'concept:name']] = df[['concept:name S1','concept:name S2','lifecycle:transition S1', 'lifecycle:transition S2', 'concept:name']].fillna('NaN')
df[['case_id S1', 'case_id S2']] = df[['case_id S1', 'case_id S2']].fillna(0)

def absolute_concept(var):
    if (var[0][0] == 'W') and (var[1][0] == 'W') and (var[0] != var[1]) and (var[2]+var[3] == 'COMPLETESCHEDULE') and (var[4] == var[5]) and (var[4] == var[5]):
            return pd.Series([var[1], 'START', 'trigger'])
        
    return pd.Series([var[7], var[8], 'no'])

In [21]:
df[['concept:name P', 'lifecycle:transition P', 'trigger_boy']] = df[['concept:name S1', 'concept:name S2','lifecycle:transition S1', 'lifecycle:transition S2', 
                           'case_id', 'case_id S1', 'case_id S2', 'concept:name', 'lifecycle:transition']].apply(absolute_concept, axis=1)

In [22]:
df[df['trigger_boy'] == 'trigger']

,case_id,step_number,org:resource,lifecycle:transition,concept:name,time:timestamp,concept:name S1,concept:name S2,lifecycle:transition S1,lifecycle:transition S2,case_id S1,case_id S2,concept:name P,lifecycle:transition P,trigger_boy
12,0,12,NaN,START,W_Nabellen offertes,2011-10-01 12:15:41.290000+02:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,0.0,0.0,W_Nabellen offertes,START,trigger
20,0,20,10629.0,START,W_Valideren aanvraag,2011-10-13 10:05:26.925000+02:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,0.0,0.0,W_Valideren aanvraag,START,trigger
40,1,14,NaN,START,W_Nabellen offertes,2011-10-01 14:36:13.443000+02:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,1.0,1.0,W_Nabellen offertes,START,trigger
55,1,29,10809.0,START,W_Valideren aanvraag,2011-10-10 11:12:36.612000+02:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,1.0,1.0,W_Valideren aanvraag,START,trigger
83,2,18,11201.0,START,W_Nabellen offertes,2011-10-03 13:40:42.469000+02:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,2.0,2.0,W_Nabellen offertes,START,trigger
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262125,13081,14,10982.0,START,W_Nabellen offertes,2012-03-01 18:27:18.861000+01:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,13081.0,13081.0,W_Nabellen offertes,START,trigger
262133,13081,22,10809.0,START,W_Valideren aanvraag,2012-03-12 16:12:08.468000+01:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,13081.0,13081.0,W_Valideren aanvraag,START,trigger
262153,13082,14,11003.0,START,W_Nabellen offertes,2012-03-02 10:10:26.397000+01:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,13082.0,13082.0,W_Nabellen offertes,START,trigger
262184,13085,7,10933.0,START,W_Completeren aanvraag,2012-03-01 20:11:14.761000+01:00,W_Afhandelen leads,W_Completeren aanvraag,COMPLETE,SCHEDULE,13085.0,13085.0,W_Completeren aanvraag,START,trigger
262192,13085,15,11119.0,START,W_Nabellen offertes,2012-03-10 12:46:22.700000+01:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,13085.0,13085.0,W_Nabellen offertes,START,trigger

In [23]:
df[df['concept:name'] != df['concept:name P']]

,case_id,step_number,org:resource,lifecycle:transition,concept:name,time:timestamp,concept:name S1,concept:name S2,lifecycle:transition S1,lifecycle:transition S2,case_id S1,case_id S2,concept:name P,lifecycle:transition P,trigger_boy
14817,659,19,NaN,SCHEDULE,W_Wijzigen contractgegevens,2011-10-20 11:11:15.149000+02:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,659.0,659.0,W_Valideren aanvraag,START,trigger
47205,2219,50,11169.0,START,W_Nabellen incomplete dossiers,2011-11-16 14:44:38.134000+01:00,W_Nabellen incomplete dossiers,W_Valideren aanvraag,COMPLETE,SCHEDULE,2219.0,2219.0,W_Valideren aanvraag,START,trigger
73700,3559,31,10909.0,START,W_Nabellen offertes,2011-12-14 19:15:39.694000+01:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,3559.0,3559.0,W_Valideren aanvraag,START,trigger
127947,6453,52,11000.0,START,W_Nabellen incomplete dossiers,2011-12-29 12:35:21.017000+01:00,W_Nabellen incomplete dossiers,W_Valideren aanvraag,COMPLETE,SCHEDULE,6453.0,6453.0,W_Valideren aanvraag,START,trigger
134976,6771,40,11009.0,COMPLETE,O_CANCELLED,2012-01-09 10:42:19.034000+01:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,6771.0,6771.0,W_Valideren aanvraag,START,trigger

In [24]:
df[df['lifecycle:transition'] != df['lifecycle:transition P']]

,case_id,step_number,org:resource,lifecycle:transition,concept:name,time:timestamp,concept:name S1,concept:name S2,lifecycle:transition S1,lifecycle:transition S2,case_id S1,case_id S2,concept:name P,lifecycle:transition P,trigger_boy
14817,659,19,NaN,SCHEDULE,W_Wijzigen contractgegevens,2011-10-20 11:11:15.149000+02:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,659.0,659.0,W_Valideren aanvraag,START,trigger
14980,670,16,11201.0,COMPLETE,W_Nabellen offertes,2011-10-17 08:26:56.826000+02:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,670.0,670.0,W_Nabellen offertes,START,trigger
47515,2233,17,NaN,COMPLETE,W_Nabellen offertes,2011-11-07 11:18:12.505000+01:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,2233.0,2233.0,W_Nabellen offertes,START,trigger
48377,2270,14,11121.0,COMPLETE,W_Nabellen offertes,2011-11-02 14:26:20.992000+01:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,2270.0,2270.0,W_Nabellen offertes,START,trigger
53411,2533,18,NaN,COMPLETE,W_Valideren aanvraag,2011-11-11 08:57:21.890000+01:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,2533.0,2533.0,W_Valideren aanvraag,START,trigger
113266,5701,12,11203.0,COMPLETE,W_Nabellen offertes,2011-12-12 16:35:22.294000+01:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,5701.0,5701.0,W_Nabellen offertes,START,trigger
134976,6771,40,11009.0,COMPLETE,O_CANCELLED,2012-01-09 10:42:19.034000+01:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,6771.0,6771.0,W_Valideren aanvraag,START,trigger
208090,10201,14,11179.0,COMPLETE,W_Nabellen offertes,2012-02-03 09:59:54.155000+01:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,10201.0,10201.0,W_Nabellen offertes,START,trigger

In [10]:
df.iloc[14814:14819]

,case_id,step_number,org:resource,lifecycle:transition,concept:name,time:timestamp,concept:name S1,concept:name S2,lifecycle:transition S1,lifecycle:transition S2,case_id S1,case_id S2,concept:name P,trigger_boy
14814,659,16,11029.0,COMPLETE,O_SENT_BACK,2011-10-17 11:10:07.948000+02:00,W_Nabellen offertes,W_Completeren aanvraag,START,COMPLETE,659.0,659.0,O_SENT_BACK,no
14815,659,17,NaN,SCHEDULE,W_Valideren aanvraag,2011-10-17 11:10:08.096000+02:00,O_SENT_BACK,W_Nabellen offertes,COMPLETE,START,659.0,659.0,W_Valideren aanvraag,no
14816,659,18,NaN,COMPLETE,W_Nabellen offertes,2011-10-17 11:10:09.274000+02:00,W_Valideren aanvraag,O_SENT_BACK,SCHEDULE,COMPLETE,659.0,659.0,W_Nabellen offertes,no
14817,659,19,NaN,START,W_Wijzigen contractgegevens,2011-10-20 11:11:15.149000+02:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,659.0,659.0,W_Valideren aanvraag,trigger
14818,659,20,10972.0,START,W_Valideren aanvraag,2011-10-21 15:15:21.648000+02:00,W_Wijzigen contractgegevens,W_Nabellen offertes,SCHEDULE,COMPLETE,659.0,659.0,W_Valideren aanvraag,no

In [11]:
df[df['case_id'] == 659]

,case_id,step_number,org:resource,lifecycle:transition,concept:name,time:timestamp,concept:name S1,concept:name S2,lifecycle:transition S1,lifecycle:transition S2,case_id S1,case_id S2,concept:name P,trigger_boy
14798,659,0,112.0,COMPLETE,A_SUBMITTED,2011-10-09 16:57:29.113000+02:00,A_DECLINED,A_PARTLYSUBMITTED,COMPLETE,COMPLETE,658.0,658.0,A_SUBMITTED,no
14799,659,1,112.0,COMPLETE,A_PARTLYSUBMITTED,2011-10-09 16:57:29.287000+02:00,A_SUBMITTED,A_DECLINED,COMPLETE,COMPLETE,659.0,658.0,A_PARTLYSUBMITTED,no
14800,659,2,112.0,SCHEDULE,W_Afhandelen leads,2011-10-09 16:57:37.787000+02:00,A_PARTLYSUBMITTED,A_SUBMITTED,COMPLETE,COMPLETE,659.0,659.0,W_Afhandelen leads,no
14801,659,3,10881.0,START,W_Afhandelen leads,2011-10-10 09:29:54.604000+02:00,W_Afhandelen leads,A_PARTLYSUBMITTED,SCHEDULE,COMPLETE,659.0,659.0,W_Afhandelen leads,no
14802,659,4,10881.0,COMPLETE,A_PREACCEPTED,2011-10-10 09:31:29.287000+02:00,W_Afhandelen leads,W_Afhandelen leads,START,SCHEDULE,659.0,659.0,A_PREACCEPTED,no
14803,659,5,10881.0,SCHEDULE,W_Completeren aanvraag,2011-10-10 09:31:29.427000+02:00,A_PREACCEPTED,W_Afhandelen leads,COMPLETE,START,659.0,659.0,W_Completeren aanvraag,no
14804,659,6,10881.0,COMPLETE,W_Afhandelen leads,2011-10-10 09:31:31.106000+02:00,W_Completeren aanvraag,A_PREACCEPTED,SCHEDULE,COMPLETE,659.0,659.0,W_Afhandelen leads,no
14805,659,7,11019.0,START,W_Completeren aanvraag,2011-10-10 12:36:07.528000+02:00,W_Afhandelen leads,W_Completeren aanvraag,COMPLETE,SCHEDULE,659.0,659.0,W_Completeren aanvraag,trigger
14806,659,8,11019.0,COMPLETE,A_ACCEPTED,2011-10-10 12:42:18.686000+02:00,W_Completeren aanvraag,W_Afhandelen leads,START,COMPLETE,659.0,659.0,A_ACCEPTED,no
14807,659,9,11019.0,COMPLETE,A_FINALIZED,2011-10-10 12:47:20.895000+02:00,A_ACCEPTED,W_Completeren aanvraag,COMPLETE,START,659.0,659.0,A_FINALIZED,no
14808,659,10,11019.0,COMPLETE,O_SELECTED,2011-10-10 12:47:20.895000+02:00,A_FINALIZED,A_ACCEPTED,COMPLETE,COMPLETE,659.0,659.0,O_SELECTED,no
14809,659,11,11019.0,COMPLETE,O_CREATED,2011-10-10 12:47:22.396000+02:00,O_SELECTED,A_FINALIZED,COMPLETE,COMPLETE,659.0,659.0,O_CREATED,no
14810,659,12,11019.0,COMPLETE,O_SENT,2011-10-10 12:47:22.426000+02:00,O_CREATED,O_SELECTED,COMPLETE,COMPLETE,659.0,659.0,O_SENT,no
14811,659,13,11019.0,SCHEDULE,W_Nabellen offertes,2011-10-10 12:47:22.633000+02:00,O_SENT,O_CREATED,COMPLETE,COMPLETE,659.0,659.0,W_Nabellen offertes,no
14812,659,14,11019.0,COMPLETE,W_Completeren aanvraag,2011-10-10 12:47:24.549000+02:00,W_Nabellen offertes,O_SENT,SCHEDULE,COMPLETE,659.0,659.0,W_Completeren aanvraag,no
14813,659,15,NaN,START,W_Nabellen offertes,2011-10-17 11:08:29.284000+02:00,W_Completeren aanvraag,W_Nabellen offertes,COMPLETE,SCHEDULE,659.0,659.0,W_Nabellen offertes,trigger
14814,659,16,11029.0,COMPLETE,O_SENT_BACK,2011-10-17 11:10:07.948000+02:00,W_Nabellen offertes,W_Completeren aanvraag,START,COMPLETE,659.0,659.0,O_SENT_BACK,no
14815,659,17,NaN,SCHEDULE,W_Valideren aanvraag,2011-10-17 11:10:08.096000+02:00,O_SENT_BACK,W_Nabellen offertes,COMPLETE,START,659.0,659.0,W_Valideren aanvraag,no
14816,659,18,NaN,COMPLETE,W_Nabellen offertes,2011-10-17 11:10:09.274000+02:00,W_Valideren aanvraag,O_SENT_BACK,SCHEDULE,COMPLETE,659.0,659.0,W_Nabellen offertes,no
14817,659,19,NaN,START,W_Wijzigen contractgegevens,2011-10-20 11:11:15.149000+02:00,W_Nabellen offertes,W_Valideren aanvraag,COMPLETE,SCHEDULE,659.0,659.0,W_Valideren aanvraag,trigger
14818,659,20,10972.0,START,W_Valideren aanvraag,2011-10-21 15:15:21.648000+02:00,W_Wijzigen contractgegevens,W_Nabellen offertes,SCHEDULE,COMPLETE,659.0,659.0,W_Valideren aanvraag,no
14819,659,21,10972.0,COMPLETE,W_Valideren aanvraag,2011-10-21 15:20:17.285000+02:00,W_Valideren aanvraag,W_Wijzigen contractgegevens,START,SCHEDULE,659.0,659.0,W_Valideren aanvraag,no
14820,659,22,10972.0,START,W_Valideren aanvraag,2011-10-21 15:24:00.933000+02:00,W_Valideren aanvraag,W_Valideren aanvraag,COMPLETE,START,659.0,659.0,W_Valideren aanvraag,no
14821,659,23,10972.0,COMPLETE,W_Valideren aanvraag,2011-10-21 15:35:55.219000+02:00,W_Valideren aanvraag,W_Valideren aanvraag,START,COMPLETE,659.0,659.0,W_Valideren aanvraag,no
14822,659,24,10972.0,START,W_Valideren aanvraag,2011-10-21 15:43:40.135000+02:00,W_Valideren aanvraag,W_Valideren aanvraag,COMPLETE,START,659.0,659.0,W_Valideren aanvraag,no
14823,659,25,10972.0,COMPLETE,W_Valideren aanvraag,2011-10-21 15:44:33.163000+02:00,W_Valideren aanvraag,W_Valideren aanvraag,START,COMPLETE,659.0,659.0,W_Valideren aanvraag,no
14824,659,26,10972.0,START,W_Valideren aanvraag,2011-10-21 15:46:13.079000+02:00,W_Valideren aanvraag,W_Valideren aanvraag,COMPLETE,START,659.0,659.0,W_Valideren aanvraag,no
14825,659,27,10972.0,SCHEDULE,W_Nabellen incomplete dossiers,2011-10-21 15:48:34.052000+02:00,W_Valideren aanvraag,W_Valideren aanvraag,START,COMPLETE,659.0,659.0,W_Nabellen incomplete dossiers,no
14826,659,28,10972.0,COMPLETE,W_Valideren aanvraag,2011-10-21 15:48:35.500000+02:00,W_Nabellen incomplete dossiers,W_Valideren aanvraag,SCHEDULE,START,659.0,659.0,W_Valideren aanvraag,no
14827,659,29,10913.0,START,W_Nabellen incomplete dossiers,2011-10-21 17:41:27.883000+02:00,W_Valideren aanvraag,W_Nabellen incomplete dossiers,COMPLETE,SCHEDULE,659.0,659.0,W_Nabellen incomplete dossiers,trigger
14828,659,30,10913.0,SCHEDULE,W_Valideren aanvraag,2011-10-21 17:44:03.561000+02:00,W_Nabellen incomplete dossiers,W_Valideren aanvraag,START,COMPLETE,659.0,659.0,W_Valideren aanvraag,no
14829,659,31,10913.0,COMPLETE,W_Nabellen incomplete dossiers,2011-10-21 17:44:06.136000+02:00,W_Valideren aanvraag,W_Nabellen incomplete dossiers,SCHEDULE,START,659.0,659.0,W_Nabellen incomplete dossiers,no
14830,659,32,10972.0,START,W_Valideren aanvraag,2011-10-22 09:57:43.792000+02:00,W_Nabellen incomplete dossiers,W_Valideren aanvraag,COMPLETE,SCHEDULE,659.0,659.0,W_Valideren aanvraag,trigger
14831,659,33,10972.0,COMPLETE,A_APPROVED,2011-10-22 10:03:22.041000+02:00,W_Valideren aanvraag,W_Nabellen incomplete dossiers,START,COMPLETE,659.0,659.0,A_APPROVED,no
14832,659,34,10972.0,COMPLETE,O_ACCEPTED,2011-10-22 10:03:22.041000+02:00,A_APPROVED,W_Valideren aanvraag,COMPLETE,START,659.0,659.0,O_ACCEPTED,no
14833,659,35,10972.0,COMPLETE,A_ACTIVATED,2011-10-22 10:03:22.042000+02:00,O_ACCEPTED,A_APPROVED,COMPLETE,COMPLETE,659.0,659.0,A_ACTIVATED,no
14834,659,36,10972.0,COMPLETE,A_REGISTERED,2011-10-22 10:03:22.042000+02:00,A_ACTIVATED,O_ACCEPTED,COMPLETE,COMPLETE,659.0,659.0,A_REGISTERED,no
14835,659,37,10972.0,COMPLETE,W_Valideren aanvraag,2011-10-22 10:03:28.798000+02:00,A_REGISTERED,A_ACTIVATED,COMPLETE,COMPLETE,659.0,659.0,W_Valideren aanvraag,no